In [2]:
import random
import numpy as np

In [84]:
def findString(string):
    array = [int(x) for x in string]
    array = np.array([list(array)])
    n = len(array)
    ones = np.ones(shape=(n,1),dtype=int)
    m1 = array.T @ ones.T - ones @ array

    return m1

def get_diagonals(matrix):
    diagonals = []
    rows, cols = matrix.shape

    # Lower diagonals
    for i in range(1, rows):
        diagonal = matrix.diagonal(offset=-i)
        if len(diagonal) >= 1:
                    diagonals.append(diagonal)

    out = []
    lsts = []
    for n, lst in enumerate(diagonals):
        flag = True
        for idx in lst:
            if idx not in [0,-1,1,-8,-9]:
                 flag = False
        
        if flag:     
            out.append((n,lst))
            lsts.append(lst)

    return out, lsts

In [85]:
def discard_wrong_strings(l: list):
    for lst in l:
        string = ''.join([str(x) for x in lst])

        # edge cases
        edge_cases = '-8-1'
        edge_cases_2 = '-1-1'

        if edge_cases in string:
            l.remove(lst)


    print(l)


def find_mag_changes(ll: list):
    for lst in ll:
        string = ''.join([str(x) for x in lst])

        for i in range(1,14):
            test_strings = '1-8'  + i * '-9' + '-1'

            if test_strings in string:
                print(f'found mag change from {10**i} to {10**(i+1)}')
            elif test_strings[1:] in string:
                print('potential mag change detected')

                index = string.index('-8')
                if string[index - 1] == 0:
                    continue
                elif string[index - 1] == 1:
                    pass


In [94]:
string = '675676'

mat = findString(string)
print(f'{mat} = matrix\n')

diagonals, lsts = get_diagonals(mat)
print(f'{diagonals}\n')

min_len = len([x for x in range(20)])
result = None
offset = None

for i in range(len(diagonals)):
    if len(diagonals[i][1]) < min_len:
        min_len = len(diagonals[i][1])
        result = diagonals[i][1]
        offset = diagonals[i][0]

print(result, offset)



if type(result) == None:
    print(string)
else:
    lst = ''.join([str(char) for char in result])
    print(offset + 1, lst)

    identifier = offset * '0' + '1'

    print(identifier)

    str_index = lst.index(identifier)

    print(str_index)

    print(f'The first number is {string[str_index:str_index + offset + 1]} at index {str_index}')


# discard_wrong_strings(lsts)
# find_mag_changes(lsts)

[[ 0 -1  1  0 -1  0]
 [ 1  0  2  1  0  1]
 [-1 -2  0 -1 -2 -1]
 [ 0 -1  1  0 -1  0]
 [ 1  0  2  1  0  1]
 [ 0 -1  1  0 -1  0]] = matrix

[(2, array([0, 0, 1])), (3, array([ 1, -1])), (4, array([0]))]

[0] 4
5 0
00001


ValueError: substring not found