In [1]:
import random
import numpy as np

In [2]:
def getMatrix(string):
    array = [int(x) for x in string]
    array = np.array([list(array)])
    n = len(array)
    ones = np.ones(shape=(n,1),dtype=int)
    m1 = array.T @ ones.T - ones @ array

    return m1

def get_diagonals(matrix):
    diagonals = []
    rows, cols = matrix.shape

    # Lower diagonals
    for i in range(1, rows):
        diagonal = matrix.diagonal(offset=-i)
        if len(diagonal) >= 1:
                    diagonals.append(diagonal)

    out = []
    lsts = []
    for n, lst in enumerate(diagonals):
        flag = True
        for idx in lst:
            if idx not in [0,-1,1,-8,-9]:
                 flag = False
        
        if flag:     
            out.append((n,lst))
            lsts.append(lst)

    return out, lsts

In [3]:
def find_mag_changes(ll: list):
    for lst in ll:
        string = ''.join([str(x) for x in lst])

        for i in range(1,14):
            test_strings = '1-8'  + i * '-9' + '-1'

            if test_strings in string:
                print(f'found mag change from {10**i} to {10**(i+1)}')
            elif test_strings[1:] in string:
                print('potential mag change detected')

                index = string.index('-8')
                if string[index - 1] == 0:
                    continue
                elif string[index - 1] == 1:
                    pass


In [4]:
def discard_wrong_strings(l: list):
    
    raw_list = [x[1] for x in l]

    for i, lst in enumerate(raw_list):
        string = ''.join([str(x) for x in lst])

        # edge cases
        edge_cases = '-8-1'
        edge_cases_2 = '-11'
        edge_cases_3 = '1-1'


        if edge_cases in string or edge_cases_2 in string or edge_cases_3 in string:
            l.pop(i)


    return [l[0]]


def discard_wrong_strings_II(offset: int, raw_list: list):
    eval = True

    seq_len = '1' + offset * '0'
    string = ''.join([str(x) for x in raw_list])

    print(string)
    # edge cases
    edge_cases = '-8-1'
    edge_cases_2 = '-11'
    edge_cases_3 = '1-1'

    if edge_cases in string or edge_cases_2 in string or edge_cases_3 in string:
        eval = False

    elif seq_len in string or seq_len[::-1] in string:
        eval = False

    if eval:
        return (offset,raw_list)
    else:
        return None

In [ ]:
string = '0001001'

mat = getMatrix(string)
print(f'{mat} = matrix\n')

diagonals, lsts = get_diagonals(mat)
print(f'{diagonals}\n')

offset, raw_list = diagonals[0]

print(raw_list)

best_sol = None

for i in range(len(diagonals)):
    offset, raw_list = diagonals[i]
    result  = discard_wrong_strings_II(offset, raw_list)

    if result is not None:
        best_sol = result

print(f'{best_sol}\n')


In [ ]:
def get_comps(matrix):
    diagonals = []
    rows, cols = matrix.shape

    # Lower diagonals
    for i in range(1, rows):
        diagonal = matrix.diagonal(offset=-i)
        if len(diagonal) >= 1:
                    diagonals.append(diagonal)

    return diagonals

In [ ]:
def construct_mag_store():
    center = 10

    output = []

    for i in range(2,15):
        string = ''.join([str(x) for x in range(center - 2, center + 2)])
        # print(string)
        mat = getMatrix(string)

        # print(mat)
        diagonals = get_comps(mat)

        # print(diagonals)
        output.append(''.join([str(x) for x in diagonals[i - 2].tolist()]))
        center *= 10

    return output


mag_feature_store = construct_mag_store()

print(mag_feature_store)
        

string = '979899100101102'

mat = getMatrix(string)
# print(f'{mat} = matrix\n')

diagonals, lsts = get_diagonals(mat)
# print(f'{diagonals}\n')

for candidate in diagonals:
    flag = True
    sol = ''.join([str(x) for x in candidate[1].tolist()])



    for i, feature in enumerate(mag_feature_store):
        if sol in mag_feature_store[i]:

            print(f'solution found at jump between {10**i} and {10**(i+1)}')
            print(sol)
            flag = False
            break
        else:
            pass
    if flag == False:
        break


In [5]:
string = '25187745922'

mat = getMatrix(string)
print(f'{mat} = matrix\n')

diagonals, lsts = get_diagonals(mat)
# print(f'{diagonals}\n')

if len(diagonals) == 0:
    print(string)

diagonals = discard_wrong_strings(diagonals)
# print(f'{diagonals}\n')




min_len = len([x for x in range(20)])
result = None
offset = None

print(f'Len diagonal {len(diagonals)}')
# print(diagonals)

for i in range(len(diagonals)):
    if len(diagonals[i][1]) < min_len:
        min_len = len(diagonals[i][1])
        result = diagonals[i][1]
        offset = diagonals[i][0]

# print(result, offset)
lst = ''.join([str(char) for char in result])



if type(result) == None:
    print(string)
elif lst == '0':
    print(f'The first number is {string[:offset + 1]} at index 0')
else:
    
    # print(offset + 1, lst)

    identifier = offset * '0' + '1'

    # print(identifier)

    str_index = lst.index(identifier)

    # print(str_index)

    print(f'The first number is {string[str_index:str_index + offset + 1]} at index {str_index}')



[[ 0 -3  1 -6 -5 -5 -2 -3 -7  0  0]
 [ 3  0  4 -3 -2 -2  1  0 -4  3  3]
 [-1 -4  0 -7 -6 -6 -3 -4 -8 -1 -1]
 [ 6  3  7  0  1  1  4  3 -1  6  6]
 [ 5  2  6 -1  0  0  3  2 -2  5  5]
 [ 5  2  6 -1  0  0  3  2 -2  5  5]
 [ 2 -1  3 -4 -3 -3  0 -1 -5  2  2]
 [ 3  0  4 -3 -2 -2  1  0 -4  3  3]
 [ 7  4  8  1  2  2  5  4  0  7  7]
 [ 0 -3  1 -6 -5 -5 -2 -3 -7  0  0]
 [ 0 -3  1 -6 -5 -5 -2 -3 -7  0  0]] = matrix

Len diagonal 1
The first number is 2518774592 at index 0


In [161]:
def findString(string):
    # Step 1 - Construct matrix using getMatrix 
    mat = getMatrix(string)

    # Step 2 - Get diagonals using get_diagonals
    diagonals, lsts = get_diagonals(mat)
    if len(diagonals) == 0:
        return string
    
    # Step 3 - Discard wrong strings using discard_wrong_strings
    diagonals = discard_wrong_strings(diagonals)

    min_len = len([x for x in range(20)])
    result = None
    offset = None

    for i in range(len(diagonals)):
        if len(diagonals[i][1]) < min_len:
            min_len = len(diagonals[i][1])
            result = diagonals[i][1]
            offset = diagonals[i][0]
